name: "🚀 Publish Plugin"

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Build
        run: |
          dotnet restore JellyfinProxy.csproj --no-cache
          dotnet build -c Release --no-restore JellyfinProxy.csproj
          zip -j JellyfinProxy.zip ./bin/Release/net9.0/JellyfinProxy.dll
      - name: Move latest tag
        run: |
          git tag -f latest
          git push --force origin latest
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: JellyfinProxy.zip
          tag_name: latest
          name: JellyfinProxy
          make_latest: true
